version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.0-node
    steps:
      - checkout
      - restore_cache:
          name: Restore vendor cache
          keys:
            - php-dependencies-{{ checksum "composer.json" }}
            - php-dependencies-
      - run:
          name: Install vendor packages
          command: |
            cp .env.pipelines .env
            sed -ie "s|__APP_ENV__|$APP_ENV|g" .env
            sed -ie "s|__APP_KEY__||g" .env
            sed -ie "s|__APP_URL__|$APP_URL|g" .env
            sed -ie "s|__DB_DATABASE__|$DB_DATABASE|g" .env
            sed -ie "s|__DB_HOST__|$DB_HOST|g" .env
            sed -ie "s|__DB_PASSWORD__|$DB_PASSWORD|g" .env
            sed -ie "s|__DB_USERNAME__|$DB_USERNAME|g" .env
            sed -ie "s|__MAILGUN_DOMAIN__|$MAILGUN_DOMAIN|g" .env
            sed -ie "s|__MAILGUN_SECRET__|$MAILGUN_SECRET|g" .env
            sed -ie "s|__MAIL_FROM_ADDRESS__|$MAIL_FROM_ADDRESS|g" .env
            composer install --no-interaction --prefer-dist
      - save_cache:
          name: Save vendor cache
          key: php-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          name: Restore node cache
          keys:
            - node-dependencies-{{ checksum "package.json" }}
            - node-dependencies-
      - run:
          name: Install node packages
          command: npm install
      - save_cache:
          name: Save node cache
          key: node-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  
  phpunit:
    docker:
      - image: cimg/php:8.0-node
      - image: circleci/mysql:5.7.31
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
          MYSQL_DATABASE: "$DB_DATABASE"
          MYSQL_USER: "$DB_USER"
          MYSQL_PASSWORD: "$DB_PASSWORD"
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Prepare production assets
          command: npm run prod
      - run: # Primary container is not MySQL so we need to wait till it's running and ready
          name: Sleep for MySQL
          command: |
            for i in `seq 1 20`
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 5
            done
            echo "Timeout waiting for connection to MySQL" && exit 1
      - run:
          name: Initialize database and environment
          command: |
            php artisan key:generate
            php artisan migrate:fresh --seed
            php artisan config:cache
            php artisan serve &
            sleep 5
      - run:
          name: Run tests
          command: |
            ./vendor/bin/phpunit --colors --testdox
      - store_artifacts:
          name: Upload logs artifacts
          path: ./storage/logs
      - store_artifacts:
          name: Upload test screenshot artifacts
          path: ./tests/Browser/screenshots
      - store_artifacts:
          name: Upload test artifacts
          path: ./tests/phpunit/results.xml
      - store_test_results:
          path: ./tests

workflows:
  deploy:
    jobs:
      - build
      - phpunit:
          requires:
            - build